#!/bin/bash
# =============================================================================
# SysGuard - Cron Job Installer
# Sets up all scheduled tasks for monitoring, backups, and log rotation
# =============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

if [[ $EUID -ne 0 ]]; then
    echo "[ERROR] This script must be run as root." >&2
    exit 1
fi

CRON_FILE="/etc/cron.d/sysguard"
LOG_DIR="/var/log/sysguard"

mkdir -p "$LOG_DIR"
chmod 750 "$LOG_DIR"

echo "[INFO] Installing SysGuard cron jobs to $CRON_FILE..."

cat > "$CRON_FILE" <<EOF
# SysGuard - Automated Monitoring & Maintenance
# Generated by install_crons.sh on $(date)
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
MAILTO=""

# System resource monitoring - every 5 minutes
*/5 * * * * root ${SCRIPT_DIR}/monitoring/system_monitor.sh >> /var/log/sysguard/monitor.log 2>&1

# Service health checks - every 2 minutes
*/2 * * * * root ${SCRIPT_DIR}/monitoring/service_health.sh check >> /var/log/sysguard/services.log 2>&1

# Log rotation - daily at 2:00 AM
0 2 * * * root ${SCRIPT_DIR}/monitoring/log_rotation.sh all >> /var/log/sysguard/rotation.log 2>&1

# Backup - daily at 1:00 AM
0 1 * * * root ${SCRIPT_DIR}/backup/backup.sh run >> /var/log/sysguard/backup.log 2>&1

# Reset service restart counters - daily at midnight
0 0 * * * root ${SCRIPT_DIR}/monitoring/service_health.sh reset >> /var/log/sysguard/services.log 2>&1

# Weekly backup verification - Sundays at 3:00 AM
0 3 * * 0 root ${SCRIPT_DIR}/backup/backup.sh report >> /var/log/sysguard/backup.log 2>&1
EOF

chmod 644 "$CRON_FILE"
echo "[INFO] Cron jobs installed successfully."
echo "[INFO] Log directory: $LOG_DIR"
echo ""
echo "Installed jobs:"
echo "  - System monitor  : every 5 minutes"
echo "  - Service health  : every 2 minutes"
echo "  - Log rotation    : daily at 02:00"
echo "  - Backup          : daily at 01:00"
echo "  - Backup report   : Sundays at 03:00"
